import "server-only";

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

// Loads firm-standard reference templates from lib/templates.generated.txt
// (gitignored, generated by `npm run templates` from templates/raw/*.docx).
// Empty fallback when the file is absent so the feature is fully opt-in —
// nothing changes for anyone who hasn't generated a templates blob.
//
// Read at module load (not per-request). Re-run `npm run templates` AND
// restart the dev server to pick up changes.

const generatedPath = join(process.cwd(), "lib", "templates.generated.txt");

export const TEMPLATES = existsSync(generatedPath)
  ? readFileSync(generatedPath, "utf8").trim()
  : "";
